name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: print current working directory
      run: pwd
    - name: change working directory
      run: cd 3_Implementation
    - name: list
      run: ls

