name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: go to implementation folder
      run: cd 3_Implementation
    - name: make
      run: make
    - name: make run
      run: make run

