name: cppcheck

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install cppcheck
      run: sudo apt-get install -y cppcheck
    - name: make
      run: make -C 3_Implementation/ all
    - name: make cppcheck
      run: make cppcheck -C 3_Implementation/

